package se.ltu.trafikgeneratorserver;

public enum Settings {
	COAP_ACK_RANDOM_FACTOR,
	COAP_ACK_TIMEOUT,
	COAP_MAX_RETRANSMIT,
	COAP_MESSAGETYPE,
	COAP_NSTART,
	COAP_PROBING_RATE,
	META_AUTHOR,
	META_TITLE,
	TEST_INTERMISSION,
	TEST_PARALLELTRANSFERS,
	TEST_REPEATS,
	TEST_SERVER,
	TEST_TESTPORT,
	TRAFFIC_BURST_TIME,
	TRAFFIC_MAXSENDTIME,
	TRAFFIC_IDLE_TIME,
	TRAFFIC_INTERMISSION,
	TRAFFIC_MAXMESSAGES,
	TRAFFIC_MESSAGESIZE,
	TRAFFIC_MODE,
	TRAFFIC_RANDOMFACTOR,
	TRAFFIC_RATE,
	TRAFFIC_TYPE
}
